package main

import (
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"trackerHub/backend/internal/api"
	"trackerHub/backend/internal/auth"
	"trackerHub/backend/internal/config"
	"trackerHub/backend/internal/models"
	"trackerHub/backend/internal/mqtt"
	"trackerHub/backend/internal/positioning"
	ws "trackerHub/backend/internal/websocket"

	_ "trackerHub/backend/docs" // This will be generated by swag
)

// @title TrackerHub API
// @version 1.0
// @description Indoor positioning system API for tracking BLE devices
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@trackerhub.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8022
// @BasePath /api
// @schemes http

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin:     func(r *http.Request) bool { return true },
}

// kalmanStore holds per-tracker Kalman filter state.
// Each tracker gets an independent filter initialized on first measurement.
var kalmanStore = models.NewKalmanStateStore()

func main() {
	// Create config manager
	configManager := config.NewConfigManager()

	// Load configurations
	runtimeConfigStore, err := config.NewRuntimeConfigStore(configManager, "config/server_runtime_config.json")
	if err != nil {
		log.Printf("Warning: Failed to load server runtime config: %v", err)
		// Create a default runtime config
		runtimeConfig := &models.ServerRuntimeConfig{
			MQTT: models.MQTTServerConfig{
				BrokerHost:    "127.0.0.1",
				BrokerPort:    1883,
				ApplicationID: "",
				TopicPattern:  "",
				Enabled:       false,
			},
			Server: models.WebServerConfig{
				Port: 8022,
			},
			Kalman: models.KalmanParams{
				ProcessVariance:     1.0,
				MeasurementVariance: 10.0,
			},
		}
		runtimeConfigStore = &config.RuntimeConfigStore{}
		runtimeConfigStore.Set(runtimeConfig)
	}
	startupRuntimeConfig := runtimeConfigStore.Get()
	if startupRuntimeConfig == nil {
		startupRuntimeConfig = &models.ServerRuntimeConfig{}
	}

	webUIConfigStore, err := config.NewWebUIConfigStore(configManager, "config/web_config.json")
	if err != nil {
		log.Printf("Warning: Failed to load web UI config: %v", err)
		// Create a default web UI config
		defaultWebUIConfig := &models.WebUIConfig{
			Map:     nil,
			Beacons: []models.WebUIBeaconConfig{},
			Settings: models.WebUISettings{
				SignalPropagationFactor: 2.5,
			},
		}
		webUIConfigStore = &config.WebUIConfigStore{}
		webUIConfigStore.Set(defaultWebUIConfig)
	}

	// Initialize components
	apiHandler := api.NewAPIHandler(configManager, runtimeConfigStore, webUIConfigStore)
	authHandler, err := api.NewAuthHandler(configManager)
	if err != nil {
		log.Fatalf("Failed to initialize auth handler: %v", err)
	}
	authConfig, err := configManager.LoadAuthConfig("config/auth_config.json")
	if err != nil {
		log.Fatalf("Failed to load auth config: %v", err)
	}
	authService := auth.NewAuthService(*authConfig)
	positioningService := positioning.NewPositioningService()
	mqttHandler := mqtt.NewMQTTHandler(&startupRuntimeConfig.MQTT, webUIConfigStore, runtimeConfigStore)
	apiHandler.SetMQTTStatusProvider(mqttHandler.GetConnectionStatus)
	wsHub := ws.NewHub()

	// Start the WebSocket hub event loop BEFORE any broadcast can be issued.
	// Broadcast* sends into an unbuffered channel that only Run() consumes;
	// sending before this goroutine starts would block forever and deadlock.
	go wsHub.Run()

	mqttHandler.SetMessageHandler(func(report *models.TrackerReport, webUIConfig *models.WebUIConfig) {
		if report == nil {
			return
		}

		timestamp := time.Now().UnixMilli()

		// Resolve the map name used for positioning (defaults to "Indoor").
		mapName := "Indoor"
		if webUIConfig != nil && webUIConfig.Map != nil && webUIConfig.Map.Name != "" {
			mapName = webUIConfig.Map.Name
		}

		enrichedBeacons := models.EnrichDetectedBeaconsWithConfig(report.DetectedBeacons, webUIConfig)
		report.DetectedBeacons = enrichedBeacons

		// Pass the tracker's previous filtered position as the multilateration
		// initial guess, matching the reference (which uses last_known_position).
		// Distance-based multilateration has mirror-image local minima that a
		// centroid start can fall into (especially with nearly-collinear beacons),
		// so seeding the solver with the last known position keeps the estimate on
		// the correct branch and enables outlier rejection against implausible jumps.
		var lastKnownPosition *[2]float64
		if prev, ok := apiHandler.GetTrackerSnapshot()[report.TrackerID]; ok && prev.Position != nil {
			px, py := prev.Position.X, prev.Position.Y
			lastKnownPosition = &[2]float64{px, py}
		}

		// Always create/update tracker state for any valid report.
		// This matches the reference IndoorPositioning behavior where a tracker
		// appears in the UI as soon as it sends data, even if position cannot be calculated.
		posResult := positioningService.CalculatePosition(report.DetectedBeacons, webUIConfig, lastKnownPosition)

		var accuracy *float64
		var filteredX, filteredY *float64
		var method string
		var confidence float64
		var beaconCount int

		if posResult != nil && posResult.Position != nil {
			// ── Kalman filtering ──────────────────────────────────────────────
			// Apply a 2-D constant-velocity Kalman filter per tracker.
			// Uses processVariance / measurementVariance from the runtime config.
			// Config changes (variance values) trigger filter reinitialization.
			runtimeCfg := runtimeConfigStore.Get()
			kalmanPV := 1.0
			kalmanMV := 10.0
			if runtimeCfg != nil {
				kalmanPV = runtimeCfg.Kalman.ProcessVariance
				kalmanMV = runtimeCfg.Kalman.MeasurementVariance
			}

			filtered := kalmanStore.Apply(
				report.TrackerID,
				posResult.Position,
				timestamp,
				kalmanPV,
				kalmanMV,
			)

			// The helper guarantees a non-nil result when posResult.Position is non-nil.
			fx := filtered[0]
			fy := filtered[1]
			filteredX = &fx
			filteredY = &fy
			// ── end Kalman filtering ──────────────────────────────────────────

			trackerCoords := []float64{fx, fy}
			acc := posResult.Accuracy
			accuracy = &acc
			method = posResult.Method
			confidence = posResult.Confidence
			beaconCount = posResult.BeaconCount
			apiHandler.UpsertTrackerStateWithData(report.TrackerID, trackerCoords, timestamp, report.DetectedBeacons, accuracy, report.Battery, posResult.UsedBeacons, mapName, &report.Timestamp)
		} else {
			// Position calculation failed (e.g., <3 beacons, no matching beacons, no config).
			// Still store the tracker state with detected beacons so it appears in UI as "Position pending".
			apiHandler.UpsertTrackerStateWithData(report.TrackerID, nil, timestamp, report.DetectedBeacons, nil, report.Battery, nil, mapName, &report.Timestamp)
		}

		// Build tracker data for WebSocket - position may be nil if positioning failed
		var positionData map[string]interface{}
		if filteredX != nil && filteredY != nil {
			positionData = map[string]interface{}{"x": *filteredX, "y": *filteredY}
		} else {
			positionData = nil // Will serialize to null in JSON
		}

		snapshot := apiHandler.GetTrackerSnapshot()
		live := snapshot[report.TrackerID]
		trackerData := map[string]interface{}{
			"trackerId":             report.TrackerID,
			"timestamp":             timestamp,
			"position":              positionData,
			"accuracy":              accuracy,
			"battery":               report.Battery,
			"confidence":            confidence,
			"method":                method,
			"beaconCount":           beaconCount,
			"last_detected_beacons": report.DetectedBeacons,
			"used_beacons":          live.UsedBeacons,
			"map":                   live.Map,
			"type":                  live.Type,
			"radius":                live.Radius,
			"sos":                   live.SOS,
			"online":                live.Online,
			"id":                    live.ID,
			"device_name":           live.DeviceName,
			"group_id":              live.GroupID,
			"is_favorite":           live.IsFavorite,
			"tracker_number":        live.TrackerNumber,
			"position_history":      live.PositionHistory,
		}

		message := map[string]interface{}{
			"type": "tracker_update",
			"data": map[string]interface{}{
				report.TrackerID: trackerData,
			},
		}

		wsHub.BroadcastMessage(message)
	})

	mqttHandler.SetErrorHandler(func(err error) {
		status := mqttHandler.GetConnectionStatus()
		if err == nil && status == "connected" {
			wsHub.BroadcastMQTTStatus("connected")
			return
		}
		if status == "disconnected" {
			wsHub.BroadcastMQTTStatus("disconnected")
			return
		}
		if status == "connecting" {
			wsHub.BroadcastMQTTStatus("connecting")
			return
		}
		if status == "disabled" {
			wsHub.BroadcastMQTTStatus("disabled")
			return
		}
		wsHub.BroadcastMQTTStatus("error")
	})

	// Connect to MQTT if enabled
	if startupRuntimeConfig.MQTT.Enabled {
		wsHub.BroadcastMQTTStatus("connecting")
		if err := mqttHandler.Connect(); err != nil {
			wsHub.BroadcastMQTTStatus("error")
			log.Printf("Failed to connect to MQTT: %v", err)
		} else {
			if err := mqttHandler.StartSubscribing(); err != nil {
				wsHub.BroadcastMQTTStatus("error")
				log.Printf("Failed to subscribe to MQTT topics: %v", err)
			}
		}
	} else {
		wsHub.BroadcastMQTTStatus("disabled")
	}

	// Set up HTTP server
	router := gin.Default()

	// Swagger endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API routes
	apiGroup := router.Group("/api")
	{
		apiGroup.POST("/login", authHandler.Login)

		authenticated := apiGroup.Group("")
		authenticated.Use(auth.AuthMiddleware(authService))
		{
			authenticated.GET("/configuration/web", apiHandler.GetWebUIConfig)
			authenticated.GET("/configuration/dashboard", apiHandler.GetDashboardConfig)
			authenticated.POST("/configuration/web", apiHandler.UpdateWebUIConfig)
			authenticated.GET("/auth-config", authHandler.GetAuthConfig)
			authenticated.POST("/auth-config", authHandler.UpdateAuthConfig)
			authenticated.GET("/server-runtime-config", apiHandler.GetServerRuntimeConfig)
			authenticated.POST("/server-runtime-config", apiHandler.UpdateServerRuntimeConfig)
			authenticated.POST("/server-runtime-config/restart", apiHandler.RestartService)
			authenticated.GET("/mqtt-status", func(c *gin.Context) {
				status := mqttHandler.GetConnectionStatus()
				if !startupRuntimeConfig.MQTT.Enabled {
					status = "disabled"
				} else if status == "" {
					status = "connecting"
				}
				c.JSON(http.StatusOK, gin.H{"status": status})
			})
			authenticated.POST("/mqtt/connect", func(c *gin.Context) {
				if err := mqttHandler.Connect(); err != nil {
					c.JSON(http.StatusInternalServerError, gin.H{"status": "error", "error": err.Error()})
					return
				}
				if err := mqttHandler.StartSubscribing(); err != nil {
					c.JSON(http.StatusInternalServerError, gin.H{"status": "error", "error": err.Error()})
					return
				}
				c.JSON(http.StatusOK, gin.H{"status": mqttHandler.GetConnectionStatus()})
			})
			authenticated.POST("/mqtt/disconnect", func(c *gin.Context) {
				mqttHandler.Disconnect()
				c.JSON(http.StatusOK, gin.H{"status": mqttHandler.GetConnectionStatus()})
			})
			authenticated.GET("/trackers", apiHandler.GetTrackers)
			authenticated.POST("/trackers", apiHandler.PostTrackerUpdate)
		}
	}

	// WebSocket endpoint
	router.GET("/ws", func(c *gin.Context) {
		token := c.Query("token")
		if token == "" {
			authorization := c.GetHeader("Authorization")
			if strings.HasPrefix(authorization, "Bearer ") {
				token = strings.TrimPrefix(authorization, "Bearer ")
			}
		}
		if token == "" {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "Missing auth token"})
			return
		}
		if _, valid := authService.ValidateToken(token); !valid {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "Invalid or expired auth token"})
			return
		}

		conn, err := upgrader.Upgrade(c.Writer, c.Request, nil)
		if err != nil {
			log.Printf("Failed to upgrade WebSocket: %v", err)
			return
		}
		client := ws.HandleWebSocket(conn, wsHub)

		// Send current initial tracker state immediately to the connected client
		client.SendMessage(map[string]interface{}{
			"type": "initial_state",
			"data": apiHandler.GetTrackerSnapshot(),
		})

		// Send current MQTT status immediately to the connected client
		mqttStatus := mqttHandler.GetConnectionStatus()
		if !startupRuntimeConfig.MQTT.Enabled {
			mqttStatus = "disabled"
		} else if mqttStatus == "" {
			mqttStatus = "connecting"
		}
		client.SendMessage(map[string]interface{}{
			"type": "mqtt_status_update",
			"data": map[string]string{"status": mqttStatus},
		})
	})

	// Start HTTP server
	serverAddr := ":" + strconv.Itoa(startupRuntimeConfig.Server.Port)
	go func() {
		if err := router.Run(serverAddr); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Failed to start server: %v", err)
		}
	}()

	log.Printf("Server started on port %d", startupRuntimeConfig.Server.Port)
	log.Printf("Swagger UI available at http://localhost:%d/swagger/index.html", startupRuntimeConfig.Server.Port)

	// Wait for interrupt signal to gracefully shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	// Cleanup
	if mqttHandler != nil {
		mqttHandler.Disconnect()
	}

	// Give some time for ongoing operations to complete
	time.Sleep(2 * time.Second)
	log.Println("Server stopped")
}
