package main

import (
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"trackerHub/backend/internal/api"
	"trackerHub/backend/internal/auth"
	"trackerHub/backend/internal/config"
	"trackerHub/backend/internal/models"
	"trackerHub/backend/internal/mqtt"
	"trackerHub/backend/internal/positioning"
	ws "trackerHub/backend/internal/websocket"

	_ "trackerHub/backend/docs" // This will be generated by swag
)

// @title TrackerHub API
// @version 1.0
// @description Indoor positioning system API for tracking BLE devices
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@trackerhub.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8022
// @BasePath /api
// @schemes http

var upgrader = websocket.Upgrader{
	ReadBufferSize:  1024,
	WriteBufferSize: 1024,
	CheckOrigin:     func(r *http.Request) bool { return true },
}

func main() {
	// Create config manager
	configManager := config.NewConfigManager()

	// Load configurations
	runtimeConfigStore, err := config.NewRuntimeConfigStore(configManager, "config/server_runtime_config.json")
	if err != nil {
		log.Printf("Warning: Failed to load server runtime config: %v", err)
		// Create a default runtime config
		runtimeConfig := &models.ServerRuntimeConfig{
			MQTT: models.MQTTServerConfig{
				BrokerHost:    "127.0.0.1",
				BrokerPort:    1883,
				ApplicationID: "",
				TopicPattern:  "",
				Enabled:       false,
			},
			Server: models.WebServerConfig{
				Port: 8022,
			},
			Kalman: models.KalmanParams{
				ProcessVariance:     1.0,
				MeasurementVariance: 10.0,
			},
		}
		runtimeConfigStore = &config.RuntimeConfigStore{}
		runtimeConfigStore.Set(runtimeConfig)
	}
	startupRuntimeConfig := runtimeConfigStore.Get()
	if startupRuntimeConfig == nil {
		startupRuntimeConfig = &models.ServerRuntimeConfig{}
	}

	webUIConfig, err := configManager.LoadWebUIConfig("config/web_config.json")
	if err != nil {
		log.Printf("Warning: Failed to load web UI config: %v", err)
		// Create a default web UI config
		webUIConfig = &models.WebUIConfig{
			Map:     nil,
			Beacons: []models.WebUIBeaconConfig{},
			Settings: models.WebUISettings{
				SignalPropagationFactor: 2.5,
			},
		}
	}

	// Initialize components
	apiHandler := api.NewAPIHandler(configManager, runtimeConfigStore)
	authHandler, err := api.NewAuthHandler(configManager)
	if err != nil {
		log.Fatalf("Failed to initialize auth handler: %v", err)
	}
	authConfig, err := configManager.LoadAuthConfig("config/auth_config.json")
	if err != nil {
		log.Fatalf("Failed to load auth config: %v", err)
	}
	authService := auth.NewAuthService(*authConfig)
	positioningService := positioning.NewPositioningService()
	mqttHandler := mqtt.NewMQTTHandler(&startupRuntimeConfig.MQTT, webUIConfig, runtimeConfigStore)
	wsHub := ws.NewHub()

	// Set up MQTT message handler
	mqttHandler.SetMessageHandler(func(report *models.TrackerReport) {
		if report == nil {
			return
		}

		// Calculate position
		position := positioningService.CalculatePosition(report.DetectedBeacons, webUIConfig, nil)
		if position != nil {
			// Create tracker update message
			trackerData := map[string]interface{}{
				"trackerId": report.TrackerID,
				"position": map[string]float64{
					"x": position[0],
					"y": position[1],
				},
				"timestamp": time.Now().UnixMilli(),
			}

			message := map[string]interface{}{
				"type": "tracker_update",
				"data": map[string]interface{}{
					report.TrackerID: trackerData,
				},
			}

			wsHub.BroadcastMessage(message)
		}
	})

	// Connect to MQTT if enabled
	if startupRuntimeConfig.MQTT.Enabled {
		if err := mqttHandler.Connect(); err != nil {
			log.Printf("Failed to connect to MQTT: %v", err)
		} else {
			if err := mqttHandler.StartSubscribing(); err != nil {
				log.Printf("Failed to subscribe to MQTT topics: %v", err)
			}
		}
	}

	// Start WebSocket hub
	go wsHub.Run()

	// Set up HTTP server
	router := gin.Default()

	// Swagger endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API routes
	apiGroup := router.Group("/api")
	{
		apiGroup.POST("/login", authHandler.Login)

		authenticated := apiGroup.Group("")
		authenticated.Use(auth.AuthMiddleware(authService))
		{
			authenticated.GET("/config/web", apiHandler.GetWebUIConfig)
			authenticated.POST("/config/web", apiHandler.UpdateWebUIConfig)
			authenticated.GET("/auth-config", authHandler.GetAuthConfig)
			authenticated.POST("/auth-config", authHandler.UpdateAuthConfig)
			authenticated.GET("/server-runtime-config", apiHandler.GetServerRuntimeConfig)
			authenticated.POST("/server-runtime-config", apiHandler.UpdateServerRuntimeConfig)
			authenticated.POST("/server-runtime-config/restart", apiHandler.RestartService)
			authenticated.GET("/trackers", apiHandler.GetTrackers)
			authenticated.POST("/trackers", apiHandler.PostTrackerUpdate)
		}
	}

	// WebSocket endpoint
	router.GET("/ws", func(c *gin.Context) {
		conn, err := upgrader.Upgrade(c.Writer, c.Request, nil)
		if err != nil {
			log.Printf("Failed to upgrade WebSocket: %v", err)
			return
		}
		ws.HandleWebSocket(conn, wsHub)
	})

	// Start HTTP server
	serverAddr := ":" + strconv.Itoa(startupRuntimeConfig.Server.Port)
	go func() {
		if err := router.Run(serverAddr); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Failed to start server: %v", err)
		}
	}()

	log.Printf("Server started on port %d", startupRuntimeConfig.Server.Port)
	log.Printf("Swagger UI available at http://localhost:%d/swagger/index.html", startupRuntimeConfig.Server.Port)

	// Wait for interrupt signal to gracefully shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	// Cleanup
	if mqttHandler != nil {
		mqttHandler.Disconnect()
	}

	// Give some time for ongoing operations to complete
	time.Sleep(2 * time.Second)
	log.Println("Server stopped")
}
